<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>queue</RootNamespace>
    <AssemblyName>0-queue</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>bin/$(Configuration)/$(TargetFramework)/0-queue.xml</DocumentationFile>
  </PropertyGroup>

</Project>
